CC = gcc-8

CFLAGS = -s -fno-plt -fno-stack-protector -fno-stack-check -fno-PIC -fno-PIE -march=nocona \
-no-pie -nostartfiles -fno-stack-protector -fno-stack-check \
-fmerge-all-constants -fomit-frame-pointer \
-funsafe-math-optimizations -ffast-math -fmerge-all-constants -fsingle-precision-constant 
CFLAGS += -malign-data=cacheline -mno-fancy-math-387 -mno-ieee-fp -fno-builtin #-flto
CFLAGS += -Os

LIBS=-lSDL2 #-lc

VNDH_FLAGS :=-l -v --vndh vondehi #--vndh_unibin
# SMOLARGS= --verbose -g -fuse-dlfixup-loader -falign-stack
SMOLARGS= -c -fuse-interp -falign-stack -fuse-dnload-loader -funsafe-dynamic -fuse-dt-debug -fno-start-arg --det

all: t2k

src/t2k.S: src/t2k.c
	gcc -S  $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
	objcopy $@ --set-section-alignment *=1 -g -x -X -S --strip-unneeded
	size $@
	# readelf -S $@

%.lzma: %.smol
	./autovndh.py $(VNDH_FLAGS) --nostub  "$<" > "$@"
	rm $<

t2k.sh: shelldropper.sh t2k.lzma
	cat $^ > $@
	chmod +x $@
	wc -c $@

t2k.smol: src/t2k.o
	python3 ./smol/smold.py --smolrt "smol/rt" --smolld "smol/ld" $(SMOLARGS)  $(LIBS) $< $@
	@stat --printf="$@: %s bytes\n" $@

t2k.cmix: t2k.smol
	cmix -c $< $@.cm
	cat cmix/cmixdropper.sh $@.cm > $@
	rm $@.cm
	chmod +x $@
	@stat --printf="$@: %s bytes\n" $@

heatmap: t2k.lzma
	../LZMA-Vizualizer/LzmaSpec $<
	@stat --printf="$@: %s bytes\n" $<
	rm $<

xlink: t2k.smol
	cat t2k.smol | ~/coding/xlink/bin/xlink

clean:
	-rm -f t2k* src/t2k.o* src/t2k.S

t2k: t2k.smol
	./autovndh.py $(VNDH_FLAGS) "$<" > "$@"
	rm $<
	chmod +x $@
	@stat --printf="$@: %s bytes\n" $@
