LIBS=-lSDL2 -lc

BITS=32
MARCH= -march=i386

SFLAGS= --strip-unneeded
SFLAGS+= -R .bss
SFLAGS+= -R .comment
SFLAGS+= -R .eh_frame
SFLAGS+= -R .eh_frame_hdr
SFLAGS+= -R .rela.dyn
SFLAGS+= -R .gnu.version
SFLAGS+= -R .gnu.hash
SFLAGS+= -R .note.gnu.build-id
SFLAGS+= -R .note.ABI-tag
SFLAGS+= -R .note.gnu.gold-version
SFLAGS+= -R .got
SFLAGS+= -R got.plt
SFLAGS+= -R .note
SFLAGS+= -R .bss
SFLAGS+= -s -S


CFLAGS= -m$(BITS) $(MARCH) -nostartfiles -nostdlib -fno-plt  -fno-stack-check -fno-stack-check -fno-stack-protector -nostartfiles -nostdlib -Os -s -ffunction-sections -fdata-sections -ffast-math -fno-exceptions -fomit-frame-pointer -fdata-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-math-errno -fno-unroll-loops -fmerge-all-constants -fno-ident -mfpmath=387 -mfancy-math-387 -Bmydir -falign-functions=1 -falign-jumps=1 -falign-loops=1 -fomit-frame-pointer -fsingle-precision-constant
LDFLAGS= -m$(BITS) -nostartfiles -nostdlib -Wl,--gc-sections -Wl,--build-id=none -Wl,--hash-style=gnu -Wl,-z,norelro

all: clean bin/tetris

obj/tetris.o:
	$(CC) -c $(LIBS) $(CFLAGS) test/tetris.c -o obj/tetris.o

bin/tetris: bin/tetris.stripped
	mv $< t
	lzma --format=lzma -9 --extreme --lzma1=preset=9,lc=0,lp=0,pb=0 --stdout t > t.lzma
	cat ~/bin/vondehi t.lzma > $@
	chmod +x $@
	wc -c $@

bin/tetris.elf: obj/tetris.o
	$(CC) $(LIBS) $(LDFLAGS) $< -o $@

bin/tetris.stripped: bin/tetris.elf
	cp $< $@
	strip $(SFLAGS) $@
	# ./Section-Header-Stripper/section-stripper.py $@
	sstrip -z $@
	-rm $<
	
clean: 
	rm -rf obj/* bin/*